# Generated by Django 2.1.7 on 2019-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comments_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
